### ISSUE TITLE
Access Request for James Strahm

### ISSUE THREAD

**Issue by TwinNumberOne** [larpchronicles/rules#61]
Access for James Strahm (Eric Everglade) to reorganize status into three categories: ability, status, and monster abiltiy

**Comment by sd0yle** [comment]
Added user to collaborators, pending invitation acceptance.  
![image](https://user-images.githubusercontent.com/6601814/223291593-ba0713b9-3750-484d-b536-afb08fe1c232.png)

**Comment by sd0yle** [comment]
Invite accepted, access established.  Closing issue.
